spring.config.import: optional:classpath:application-common.yml

server:
  port: 8086

spring:
  application:
    name: aiot-data-parser

aiot:
  security:
    validate:
      entries: "aiot.internal.token:24"
