package com.aiot.device.dto;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class AdminConsoleOverviewResp {
    private Integer homeCount;
    private Integer memberCount;
    private Integer productCount;
    private Integer deviceCount;
    private Integer otaTaskCount;
    private Integer todayAlarmCount;
    private Integer pendingWorkOrderCount;
    private Double oneTimeResolveRate;
    private Integer aiEvalReadyCount;
    private Integer aiEvalPassedCount;
    private Long aiEvalLastGeneratedAt;
    private Boolean aiPersistenceMysqlEnabled;
    private String aiPersistenceReadMode;
    private String aiPersistenceConfiguredReadMode;
    private Boolean aiPersistenceMysqlReady;
    private Boolean aiPersistenceMysqlCutoverReady;
    private String aiPersistenceMysqlCutoverBlockReason;
    private Boolean aiPersistenceBackfillManifestExists;
    private Integer aiPersistenceBackfillWrittenTotal;
    private Boolean aiPersistenceConsistencyReportExists;
    private Boolean aiPersistenceConsistencyPassed;
    private Integer aiPersistenceConsistencyTotalMismatch;
    private Boolean aiPersistenceConstraintsReportExists;
    private Boolean aiPersistenceConstraintsGatePassed;
    private Integer aiPersistenceConstraintsFailedCount;
    private Boolean aiPersistenceMigrationGatePassed;
    private String aiPersistenceMysqlWriteOutboxStoreMode;
    private Integer aiPersistenceMysqlWriteOutboxLegacyRedisPendingCount;
    private Boolean aiPersistenceMysqlWriteOutboxReplayEnabled;
    private Integer aiPersistenceMysqlWriteOutboxReplayBatchSize;
    private Long aiPersistenceMysqlWriteOutboxReplayFixedDelayMs;
    private Integer aiPersistenceMysqlWriteOutboxPendingCount;
    private Long aiPersistenceMysqlWriteOutboxOldestAgeSeconds;
    private String aiPersistenceCaseMaterializationStoreMode;
    private Integer aiPersistenceCaseMaterializationLegacyRedisPendingCount;
    private Boolean aiPersistenceCaseMaterializationReplayEnabled;
    private Integer aiPersistenceCaseMaterializationReplayBatchSize;
    private Long aiPersistenceCaseMaterializationReplayFixedDelayMs;
    private Integer aiCaseMaterializationPendingCount;
    private Long aiCaseMaterializationOldestAgeSeconds;
    private Boolean aiPersistenceControlPlaneRedisDrainCompleted;
    private Boolean aiPersistenceBusinessLiveFlowReportExists;
    private String aiPersistenceBusinessLiveFlowReportPath;
    private Long aiPersistenceBusinessLiveFlowVerifiedAt;
    private String aiPersistenceBusinessLiveFlowScene;
    private Boolean aiPersistenceBusinessLiveFlowSuccess;
    private String aiPersistenceBusinessLiveFlowDeviceId;
    private String aiPersistenceBusinessLiveFlowGlobalDeviceId;
    private String aiPersistenceBusinessLiveFlowAuthIdentity;
    private String aiPersistenceBusinessLiveFlowDeviceSn;
    private String aiPersistenceBusinessLiveFlowEventId;
    private String aiPersistenceBusinessLiveFlowDiagnosisId;
    private String aiPersistenceBusinessLiveFlowFeedbackId;
    private String aiPersistenceBusinessLiveFlowCaseId;
    private Integer aiPersistenceBusinessLiveFlowMysqlWriteOutboxCount;
    private Integer aiPersistenceBusinessLiveFlowCaseMaterializationTaskCount;
    private Boolean aiPersistenceBusinessLiveFlowDiagnosisMirrorExists;
    private Boolean aiPersistenceBusinessLiveFlowFeedbackMirrorExists;
    private Boolean aiPersistenceBusinessLiveFlowCaseMirrorExists;
    private Long aiPersistenceControlPlaneLastDrainAt;
    private String aiPersistenceControlPlaneLastDrainOperator;
    private Boolean aiPersistenceControlPlaneLastDrainDryRun;
    private Boolean aiPersistenceControlPlaneLastDrainAccepted;
    private String aiPersistenceControlPlaneLastDrainMessage;
    private Boolean aiPersistenceControlPlaneDrainReportExists;
    private String aiPersistenceControlPlaneDrainReportPath;
    private String aiPersistenceControlPlaneDrainReportSource;
    private Long aiPersistenceControlPlaneDrainReportExecutedAt;
    private String aiPersistenceControlPlaneDrainReportOperator;
    private Boolean aiPersistenceControlPlaneDrainReportDryRun;
    private Boolean aiPersistenceControlPlaneDrainReportAccepted;
    private Integer aiPersistenceControlPlaneDrainReportBatchSize;
    private String aiPersistenceControlPlaneDrainReportRequestedStores;
    private String aiPersistenceControlPlaneDrainReportMessage;
    private Integer aiPersistenceControlPlaneDrainReportMysqlWriteOutboxRedisPending;
    private Integer aiPersistenceControlPlaneDrainReportMysqlWriteOutboxMysqlWritten;
    private Integer aiPersistenceControlPlaneDrainReportMysqlWriteOutboxRedisRemaining;
    private Integer aiPersistenceControlPlaneDrainReportCaseMaterializationRedisPending;
    private Integer aiPersistenceControlPlaneDrainReportCaseMaterializationMysqlWritten;
    private Integer aiPersistenceControlPlaneDrainReportCaseMaterializationRedisRemaining;
}
