spring.config.import: optional:classpath:application-common.yml

server:
  port: 8085
  netty:
    connection-timeout: 30s
    idle-timeout: 60s
  error:
    include-stacktrace: never

spring:
  application:
    name: aiot-mqtt-adapter
    version: ${APP_VERSION:1.0.0}
    env: ${SPRING_PROFILES_ACTIVE:dev}

aiot:
  security:
    validate:
      entries: "aiot.internal.token:24"
