spring.config.import: optional:classpath:application-common.yml

server:
  port: 8087

spring:
  application:
    name: aiot-shadow-service

aiot:
  events:
    device-status-stream-group: ${AIOT_SHADOW_EVENTS_DEVICE_STATUS_STREAM_GROUP:aiot-shadow-service-group}
