package com.aiot.common.event;

public enum DeviceEventType {
    DEVICE_ONLINE,
    DEVICE_OFFLINE,
    DEVICE_PROVISION_SUCCEEDED,
    DEVICE_PROVISION_REJECTED,
    DEVICE_PROVISION_FAILED,
    SHADOW_DESIRED_UPDATED,
    SHADOW_REPORTED_UPDATED
}
